config/routes.rb
Rails.application.routes.draw do
  resources :brews
  
  root 'brews#index'
end

app/models/brew.rb
class Brew < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brews_controller.rb
class BrewsController < ApplicationController
  before_action :find_brew, only: [:show, :edit, :update, :destroy]
 
  def index
    @brew = Brew.all.order("created_at DESC")
  end
  
  def show
  end
  
  def new
    @brew = Brew.new
  end
  
  def create
    @brew = Brew.new(brew_params)
    
    if @brew.save
      redirect_to @brew, notice: "Your brew was added, cheers!" 
    else
      render 'new'
    end
  end
  
  def edit

  end
  
  def update
    if @brew.update(brew_params)
      redirect_to @brew, notice: " Brew was updated, Cheers!"
    else
      render 'edit'
    end
  end
  
  def destroy
    @brew.destroy
    redirect_to root_path
  end
  
  private
  
  def brew_params
    params.require(:brew).permit(:name, :description, :location, :tagger)
  end
  
  def find_brew
    @brew = Brew.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brews_helper.rb
module BrewsHelper
end

app/views/brews/_form.html.haml
= simple_form_for @brew, html: { multipart: true } do |f|
  - if @brew.errors.any?
    #errors
      %h2
      = pluralize(@brew.errors.count, "error")
      prevented this Brew from being added
      %ul
        - @brew.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :name, input_html: { class: 'form-control' }
  .form-group
    = f.input :description, input_html: { class: 'form-control' }
  .form-group
    = f.input :location, input_html: { class: 'form-control' }
  .form-group
    = f.input :tagger, input_html: { class: 'form-control' }
    
  = f.button :submit, class: "btn btn-primary"
        
      

app/views/brews/edit.html.haml
%h1 Edit Brew
= render 'form'

= link_to "Cancel", root_path

app/views/brews/index.html.haml
= link_to "New Beer", new_brew_path
- @brew.each do |brew|
  %h2= link_to brew.name, brew

app/views/brews/new.html.haml
%h1 New Beer

= render 'form'

= link_to 'Back', root_path

app/views/brews/show.html.haml
%h1= @brew.name
%p= @brew.description
%p= @brew.location
%p= @brew.tagger
= link_to "Back", root_path
= link_to "Edit", edit_brew_path
= link_to "Delete", brew_path, method: :delete, data: { confirm: "Are you sure?" }

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Brew Me
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true 
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tag
%body
  - flash.each do |name, msg|
    = content_tag :div, msg, class: "alert alert-info"
  = yield 